### ISSUE TITLE
Can use it on linux or mac?

### ISSUE THREAD

**Issue by weaming** [DCjanus/ThunderSubs#2]
As the title.

**Comment by DCjanus** [comment]
抱歉，暂时不能。
Electron版可以使用，但可能需要自己构建。因为打包后应用较大，不太适合上传至GitHub。

PS：考虑到这个项目的使用者大概都会是中国人，也就用中文回复了，不必拘谨。

**Comment by weaming** [comment]
其实可以用 python 版本了
