### ISSUE TITLE
下载的字幕只有1k大小

### ISSUE THREAD

**Issue by xbajiu** [DCjanus/ThunderSubs#7]
内容为

xml version="1.0" encoding="UTF-8"?
  Error
  <Code>NoSuchKey</Code>
  <Message>The specified key does not exist.</Message>
  <RequestId>645F5E68F27D8736328935EC</RequestId>
  <HostId>xlppc-subtitle.oss-cn-shanghai-internal.aliyuncs.com</HostId>
  <Key>DF/D7/DFD70800B7490D96A135A7CC39D5A74CB618578A.ass</Key>
  <EC>0026-00000001</EC>
/Error
![屏幕截图 2023-05-13 174321](https://github.com/DCjanus/ThunderSubs/assets/63810600/419bc096-0136-4a3c-8f4e-da3798f13536)

**Comment by DCjanus** [comment]
迅雷已经下线该接口了，没办法继续白嫖了
